<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="DESKTOP-CIM2M57" name="Demo_Framework.execution.TC_4_verify_balanceSheet_report" tests="2" failures="0" timestamp="17 Dec 2018 10:00:31 GMT" time="29.632" errors="1">
  <testcase name="feature" time="29.607" classname="Demo_Framework.execution.TC_4_verify_balanceSheet_report"/>
  <testcase name="tearDownClass" time="0.025" classname="Demo_Framework.execution.TC_4_verify_balanceSheet_report">
    <error type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at com.assetvantage.commonUtils.cucumberReportAfterExecution.<init>(cucumberReportAfterExecution.java:25)
at Demo_Framework.execution.TC_4_verify_balanceSheet_report.tearDownClass(TC_4_verify_balanceSheet_report.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:59)
at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:455)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:222)
at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:142)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:214)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </error>
  </testcase> <!-- tearDownClass -->
</testsuite> <!-- Demo_Framework.execution.TC_4_verify_balanceSheet_report -->
